name: compile and run colitest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        # os: [ubuntu-latest]
        os: [ubuntu-latest, macos-latest]
        toolchain:
          - {compiler: intel-classic, version: '2021.1'}
          - {compiler: intel-classic, version: '2021.2'}
          - {compiler: intel-classic, version: '2021.3'}
          - {compiler: intel-classic, version: '2021.4'}
          - {compiler: intel-classic, version: '2021.5'}
          - {compiler: intel-classic, version: '2021.6'}
          - {compiler: intel-classic, version: '2021.7'}
          - {compiler: intel-classic, version: '2021.7.1'}
          - {compiler: intel-classic, version: '2021.8'}
          - {compiler: intel-classic, version: '2021.9'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: intel, version: '2021.1'}
          - {compiler: intel, version: '2021.1.2'}
          - {compiler: intel, version: '2021.2'}
          - {compiler: intel, version: '2021.4'}
          - {compiler: intel, version: '2022.0'}
          - {compiler: intel, version: '2022.1'}
          - {compiler: intel, version: '2022.2'}
          - {compiler: intel, version: '2022.2.1'}
          - {compiler: intel, version: '2022.2'}
          - {compiler: intel, version: '2023.0'}
          - {compiler: intel, version: '2023.1'}
          - {compiler: intel, version: '2023.2'}
        exclude:
          - os: ubuntu-latest
            toolchain: {compiler: intel-classic, version: '2021.3'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2021.1.2'}
          - os: macos-latest
            toolchain: {compiler: intel-classic, version: '2021.5'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2022.0'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2022.1'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2022.2'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2022.2.1'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2023.0'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2023.1'}
          - os: macos-latest
            toolchain: {compiler: intel, version: '2023.2'}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src
          build
          powr
          test
    - name: get fortran compiler
      uses: iulusoy/setup-fortran@v0.1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        install_mkl: "true"
    - name: get compiler version
      run: ${{ env.FC }} --version
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}
    - name: compile powr
      run: |
        make intel_classic
        make clean_build
        make intel_classic_debug
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: set up the job and run base tests
      run: |
        echo "MKLROOT $MKLROOT"
        echo "MKLLIB $MKLLIB"
        echo "DYLDLIB $DYLD_LIBRARY_PATH"
        python -m pytest -svv test/test_colitest.py --cov=. --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
