name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain:
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: intel-classic, version: '2021.9'}
          - {compiler: intel-classic, version: '2021.8'}
          - {compiler: intel-classic, version: '2021.7.1'}
          - {compiler: intel-classic, version: '2021.7'}
          - {compiler: intel-classic, version: '2021.6'}
          - {compiler: intel-classic, version: '2021.5'}
          - {compiler: intel-classic, version: '2021.4'}
          - {compiler: intel-classic, version: '2021.3'}
          - {compiler: intel-classic, version: '2021.2'}
          - {compiler: intel-classic, version: '2021.1'}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: get fortran compiler
      uses: iulusoy/setup-fortran@v0
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
    - name: get compiler version
      run: ${{ env.FC }} --version
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}
    - name: compile powr
      run: |
        cd src
        make