name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]
        toolchain:
          - {compiler: intel-classic, version: '2021.10'}
          # - {compiler: intel-classic, version: '2021.1'}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src
          powr
    - name: get fortran compiler
      uses: iulusoy/setup-fortran@v0
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
    - name: get compiler version
      run: ${{ env.FC }} --version
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}
    - name: compile powr
      run: |
        cd src
        make
    - name: create folder structure
      run: |
        mkdir powr/exe_dev.dir
        cp src/*.opt powr/exe_dev.dir/.
        pwd
        ls
    - name: set up environment
      run: |
        cp pwr/.powrconfig .
        source .powrconfig
        source powr/proc.dir/bash_setup
        # csh_setup for MacOS?
    - name: create chain
      run: |
        makechain 1
    - name: run colitest
      run: | 
        sub colitest1
