name: compile and run coli integation test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]
        toolchain:
          - {compiler: intel-classic, version: '2021.10'}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src
          build
          powr
          test
    - name: get fortran compiler
      uses: iulusoy/setup-fortran@v0
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
    - name: get compiler version
      run: ${{ env.FC }} --version
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}
    - name: compile powr
      run: |
        make
        rm build/*.o
        make debug_all
    # - name: get the test models
      # run: | 
        # wget -O testmodels.tgz https://heibox.uni-heidelberg.de/f/a62c7ae5559d43a0a8b2/?dl=1
        # tar -xzf testmodels.tgz
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: run integration tests
      run: |
        python -m pytest -svv test/test_wrstart.py
